# Generated by Django 5.2.4 on 2025-07-15 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist_dash', '0002_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentistprofile',
            name='patients',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'patient'}, related_name='dentists', to=settings.AUTH_USER_MODEL),
        ),
    ]
