# Generated by Django 5.2.4 on 2025-07-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_priority',
            field=models.CharField(choices=[('low', 'Low'), ('high', 'High'), ('emergency', 'Emergency')], default='low', max_length=10),
        ),
    ]
