# Generated by Django 5.2.4 on 2025-07-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dash', '0004_testreport_approved_testreport_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='test_reports/'),
        ),
        migrations.DeleteModel(
            name='TestReportImage',
        ),
    ]
